// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://voiubdiyatvoggmlmxqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvaXViZGl5YXR2b2dnbWxteHFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3NjczODQsImV4cCI6MjA1NDM0MzM4NH0.EhdUTsi7Ze8wNPhGt8Q-efQ5gRyczYnCzBnabTsBgj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);